apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-gcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nexus-docker.flowfactor.be/mijnen_nginx:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regsecret
        volumeMounts:
        - name: ocp-persistent-storage
          mountPath: /ocp
      volumes:
      - name: ocp-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-test
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  type: LoadBalancer
