apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nexus-docker.flowfactor.be/mijnen_world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default
spec:
  ports:
  - port: 80
    nodePort: 30000
  selector:
    app: hello-world
  type: NodePort
